Update to poetry v1.6.1 in release-python.yml (#237)
To try and fix the release error:

https://github.com/cucumber/cucumber-expressions/actions/runs/6432369369/job/17467078344

```
Run poetry publish

  ImportError

  cannot import name 'appengine' from 'urllib3.contrib' (/home/runner/.local/venv/lib/python3.10/site-packages/urllib3/contrib/__init__.py)

  at ~/.local/venv/lib/python3.10/site-packages/requests_toolbelt/_compat.py:50 in <module>
       46│ else:
       47│     try:
       48│         from requests.packages.urllib3.contrib import appengine as gaecontrib
       49│     except ImportError:
    →  50│         from urllib3.contrib import appengine as gaecontrib
       51│ 
       52│ if requests.__build__ < 0x021200:
       53│     PyOpenSSLContext = None
       54│ else:
```       


The root cause is that requests_toolbelt < v1.0 and urllib3 >= 2.0 is used
together. These packages are not dependencies of cucumber-expressions, so
it must be poetry which uses them and define their versions.

These comments indicate that an updated to a later version of poetry should
fix the problem:

https://github.com/psf/requests/issues/6441#issuecomment-1633151880